Multiple parameter recipes fix.
Parameters iteration cycle in SetupMapper._check_interface_compatibility()
lacks 'iteritems' method call resulting in ValueError exception:
    Traceback (most recent call last):
      File "/usr/bin/lnst-ctl", line 102, in get_recipe_result
        nettestctl.provision_machines()
      File "/usr/lib/python2.6/site-packages/lnst/Controller/NetTestController.py", line 213, in provision_machines
        if not sp.provision_machines(machines):
      File "/usr/lib/python2.6/site-packages/lnst/Controller/SlavePool.py", line 226, in provision_machines
        res = mapper.match()
      File "/usr/lib/python2.6/site-packages/lnst/Controller/SlavePool.py", line 399, in match
        if self._if_match():
      File "/usr/lib/python2.6/site-packages/lnst/Controller/SlavePool.py", line 469, in _if_match
        if self._check_interface_compatibility(req_if, pool_if):
      File "/usr/lib/python2.6/site-packages/lnst/Controller/SlavePool.py", line 544, in _check_interface_compatibility
        for param, value in req_if["params"]:
    ValueError: too many values to unpack

Introduced in 2cc9c639ea139a4ca339850371ed65dbcd9ca93e: "SlavePool:
SetupMapper reimplementation"

Signed-off-by: Artem Savkov <asavkov@redhat.com>
Signed-off-by: Jiri Pirko <jiri@resnulli.us>