active-backup bonding primary option fix
Netdevice's id is alphanumeric, not just digits, so when calling
get_mapped_device() this id shouldn't be converted to int.
Otherwise a ValueError exception is raised:

CommandException: CommandException: Slave bondmaster: invalid literal
for int() with base 10: 'eth1'

Signed-off-by: Artem Savkov <asavkov@redhat.com>
Signed-off-by: Jiri Pirko <jiri@resnulli.us>