Fix query for libvirt_domain in non-virt scenarios
When using non-virtual machines the controller would fail with following
error:

    Traceback (most recent call last):
      File "./lnst-ctl", line 93, in get_recipe_result
        defined_aliases, overriden_aliases)
      File "./lnst-ctl", line 74, in process_recipe
        overriden_aliases=overriden_aliases)
      File "/mnt/testarea/lnst/lnst/Controller/NetTestController.py",
line 60, in __init__
        check_process_running("libvirtd"), pool_checks)
      File "/mnt/testarea/lnst/lnst/Controller/SlavePool.py", line 47,
in __init__
        self.add_dir(pool_dir)
      File "/mnt/testarea/lnst/lnst/Controller/SlavePool.py", line 55,
in add_dir
        res.append(self.add_file("%s/%s" % (pool_dir, dirent)))
      File "/mnt/testarea/lnst/lnst/Controller/SlavePool.py", line 96,
in add_file
        pm["libvirt_domain"] == rm["libvirt_domain"]:
    KeyError: 'libvirt_domain'

This was introduced by commit 2ed4e1e80de597309833a2b144682a63fcea3e74

Bare metal systems in pool do not have this parameter and therefore
parsing their slavemachine xml would fail.

As a first step I've split the hostname and libvirt_domain param check as
they are not tied together.

Next, the fix first checks whether the optional parameter libvirt_domain
exists then it checks it's value. I've tested this patch on our
regression-test machine.

Fixes issue #47.

Signed-off-by: Jiri Pirko <jiri@resnulli.us>