Fix module-tool dependency issue during resource synchronization
Version 2 of the patch. The change is that an user does not need to
specify the used tools they're retrieved from python-parsed source of
the test module.

Tested on TCPConnection module, works fine.

Original issue description:

We have currently two test modules that have dependency on a test_tool,
TCPConnection and Multicast which are wrappers around tcp_conn and
multicast test tools.

Reduced synchronization feature introduced a dependency bug. Since the
test module used in an lnst recipe does not have any information about
required test tool such tool will not be synchronized to lnst slave and
will end with an Exception like this:

Exception: CommandException: Tools 'tcp_conn' not found

Signed-off-by: Jan Tluka <jtluka@redhat.com>
Signed-off-by: Jiri Pirko <jiri@resnulli.us>