lnst.Common.DeviceError: define the DeviceReadOnly exception
This exception will be used by the RemoteDevice class when the instance
was set to the caching read only mode and the user attempted to call a
method or assign a value to an attribute.

Signed-off-by: Ondrej Lichtner <olichtne@redhat.com>