Devices/Device.py: fix eswitch check
For devices that do not support bus_info, we need to raise
DeviceFeatureNotSupported to avoid raising DeviceError and breaking
proper device cleanup:

```
Traceback (most recent call last):
  File ".../lnst/Controller/Controller.py", line 227, in _cleanup_agents
    machine.cleanup()
  File ".../lnst/Controller/Machine.py", line 492, in cleanup
    self.cleanup_devices()
  File ".../lnst/Controller/Machine.py", line 444, in cleanup_devices
    self._set_readonly_cache_for_all_devices(self._initns)
  File ".../lnst/Controller/Machine.py", line 465, in _set_readonly_cache_for_all_devices
    dev.enable_readonly_cache()
  File ".../lnst/Devices/RemoteDevice.py", line 63, in enable_readonly_cache
    for name, val in self:
  File ".../lnst/Devices/RemoteDevice.py", line 170, in __iter__
    yield (x, getattr(self, x))
  File ".../lnst/Devices/RemoteDevice.py", line 146, in __getattr__
    return self._machine.remote_device_getattr(self.ifindex, name, self.netns)
  File ".../lnst/Controller/Machine.py", line 213, in remote_device_getattr
    return self.rpc_call("dev_getattr", index, attr_name, netns=netns)
  File ".../lnst/Controller/Machine.py", line 341, in rpc_call
    return self._msg_dispatcher.send_message(self, msg)
  File ".../lnst/Controller/MessageDispatcher.py", line 127, in send_message
    self._process_message(msg)
  File ".../lnst/Controller/MessageDispatcher.py", line 224, in _process_message
    raise message[1]["Exception"]
lnst.Common.DeviceError.DeviceError: Error while querying device t_br0 eswitch mode:
Wrong identification string format.
Devlink identification ("bus_name/dev_name") expected
```

Signed-off-by: Jan Tluka <jtluka@redhat.com>